function CRISPRi_Plot(t, mrnaC, C, R, B, mrnaY)
% Create similar plots without wasting space in CRISPRi_model.m
    figure;
    hold on
    plot(t, mrnaC, 'color', [0.77 0.85 0.89], 'Linewidth', 1.5)
    plot(t, C, 'color', [0.39 0.58 0.93], 'Linewidth', 1.5)
    plot(t, R, 'color', [0.88 0.24 0.19], 'Linewidth', 1.5)
    plot(t, B, 'color', [0.42 0.19 0.51], 'Linewidth', 1.5)
    plot(t, mrnaY, 'color', [0.98 0.93 0.36], 'Linewidth', 1.5)
    legend('dCas9 mRNA', 'dCas9', 'sgRNA', 'dCas9-sgRNA Complex',...
        'YFP mRNA', 'Location','East')
    xlabel('Time (minutes)')
    ylabel('Concentration (nM)')
    set(gca, ...
      'Box'         , 'off'     , ...
      'TickDir'     , 'out'     , ...
      'TickLength'  , [.001 .001] , ...
      'XMinorTick'  , 'on'      , ...
      'YMinorTick'  , 'on'      , ...
      'YGrid'       , 'on'      , ...
      'XColor'      , [.3 .3 .3], ...
      'YColor'      , [.3 .3 .3], ...
      'YTick'       , 0:0.2:2, ...
      'LineWidth'   , 1         );
end
